import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { QueryClient, QueryClientProvider, useQuery, useQueryClient } from 'react-query'
import { request, gql } from "graphql-request";

const endpoint = 'https://graphqlzero.almansi.me/api'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
      </main>

     
    </div>
  )
}

export default Home
